<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ingredient;

class IngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ingredient::truncate();

        $ingredients=[
        ['name' =>'5 spice powder','apiIngredientId'=>'1002002'],
            ['name' =>'acorn squash','apiIngredientId'=>'11482'],
            ['name' =>'adobo sauce','apiIngredientId'=>'6979'],
            ['name' =>'agave nectar','apiIngredientId'=>'19912'],
            ['name' =>'ahi tuna','apiIngredientId'=>'15117'],
            ['name' =>'alfredo pasta sauce','apiIngredientId'=>'93606'],
            ['name' =>'almond extract','apiIngredientId'=>'1002050'],
            ['name' =>'almond flour','apiIngredientId'=>'93740'],
            ['name' =>'almond milk','apiIngredientId'=>'93607'],
            ['name' =>'almonds','apiIngredientId'=>'12061'],
            ['name' =>'amaretto','apiIngredientId'=>'10014534'],
            ['name' =>'ancho chiles','apiIngredientId'=>'10211962'],
            ['name' =>'anchovies','apiIngredientId'=>'15001'],
            ['name' =>'andouille sausage','apiIngredientId'=>'7064'],
            ['name' =>'angel food cake mix','apiIngredientId'=>'18087'],
            ['name' =>'angel hair pasta','apiIngredientId'=>'10020420'],
            ['name' =>'angostura bitters','apiIngredientId'=>'93653'],
            ['name' =>'apple','apiIngredientId'=>'9003'],
            ['name' =>'apple butter spread','apiIngredientId'=>'19294'],
            ['name' =>'apple cider','apiIngredientId'=>'1009016'],
            ['name' =>'apple juice','apiIngredientId'=>'9016'],
            ['name' =>'apple pie spice','apiIngredientId'=>'1042035'],
            ['name' =>'apricot preserves','apiIngredientId'=>'19719'],
            ['name' =>'apricots','apiIngredientId'=>'9021'],
            ['name' =>'arborio rice','apiIngredientId'=>'10020052'],
            ['name' =>'arrowroot powder','apiIngredientId'=>'20003'],
            ['name' =>'artichoke heart quarters','apiIngredientId'=>'93828'],
            ['name' =>'artichokes','apiIngredientId'=>'11007'],
            ['name' =>'arugula','apiIngredientId'=>'11959'],
            ['name' =>'asafoetida','apiIngredientId'=>'1032035'],
            ['name' =>'asafoetida powder','apiIngredientId'=>'0'],
            ['name' =>'asiago cheese','apiIngredientId'=>'1001033'],
            ['name' =>'asian pear','apiIngredientId'=>'9252'],
            ['name' =>'asparagus spears','apiIngredientId'=>'11011'],
            ['name' =>'avocado','apiIngredientId'=>'9037'],
            ['name' =>'avocado oil','apiIngredientId'=>'4581'],
            ['name' =>'baby bell peppers','apiIngredientId'=>'10311821'],
            ['name' =>'baby bok choy','apiIngredientId'=>'93636'],
            ['name' =>'baby carrots','apiIngredientId'=>'11960'],
            ['name' =>'baby corn','apiIngredientId'=>'10011168'],
            ['name' =>'baby spinach leaves','apiIngredientId'=>'11457'],
            ['name' =>'baby-back ribs','apiIngredientId'=>'10010204'],
            ['name' =>'baby-back ribs','apiIngredientId'=>'10192'],
            ['name' =>'bacon','apiIngredientId'=>'10123'],
            ['name' =>'bacon fat','apiIngredientId'=>'4609'],
            ['name' =>'baguette','apiIngredientId'=>'18033'],
            ['name' =>'baking bar','apiIngredientId'=>'19078'],
            ['name' =>'baking powder','apiIngredientId'=>'18371'],
            ['name' =>'baking soda','apiIngredientId'=>'18372'],
            ['name' =>'balsamic glaze','apiIngredientId'=>'98998'],
            ['name' =>'balsamic vinegar','apiIngredientId'=>'2069'],
            ['name' =>'bamboo shoots','apiIngredientId'=>'11028'],
            ['name' =>'banana','apiIngredientId'=>'9040'],
            ['name' =>'basmati rice','apiIngredientId'=>'10020444'],
            ['name' =>'bay leaves','apiIngredientId'=>'2004'],
            ['name' =>'bbq sauce','apiIngredientId'=>'6150'],
            ['name' =>'beans','apiIngredientId'=>'16069'],
            ['name' =>'beef','apiIngredientId'=>'23572'],
            ['name' =>'beef brisket','apiIngredientId'=>'13023'],
            ['name' =>'beef broth','apiIngredientId'=>'6008'],
            ['name' =>'beef chuck roast','apiIngredientId'=>'13786'],
            ['name' =>'beef stock','apiIngredientId'=>'6170'],
            ['name' =>'beef tenderloin','apiIngredientId'=>'13926'],
            ['name' =>'beer','apiIngredientId'=>'14003'],
            ['name' =>'beer','apiIngredientId'=>'14006'],
            ['name' =>'beets','apiIngredientId'=>'11080'],
            ['name' =>'bell pepper','apiIngredientId'=>'10211821'],
            ['name' =>'berries','apiIngredientId'=>'1009054'],
            ['name' =>'biscuit mix','apiIngredientId'=>'18010'],
            ['name' =>'biscuits','apiIngredientId'=>'18009'],
            ['name' =>'bittersweet chocolate','apiIngredientId'=>'19903'],
            ['name' =>'black bean sauce','apiIngredientId'=>'99210'],
            ['name' =>'black beans','apiIngredientId'=>'16015'],
            ['name' =>'black olives','apiIngredientId'=>'1059195'],
            ['name' =>'black pepper','apiIngredientId'=>'1002030'],
            ['name' =>'black sesame seeds','apiIngredientId'=>'10012023'],
            ['name' =>'blackberries','apiIngredientId'=>'9042'],
            ['name' =>'blanched almonds','apiIngredientId'=>'12062'],
            ['name' =>'blood orange','apiIngredientId'=>'1009200'],
            ['name' =>'blue cheese','apiIngredientId'=>'1004'],
            ['name' =>'blueberries','apiIngredientId'=>'9050'],
            ['name' =>'bok choy','apiIngredientId'=>'11116'],
            ['name' =>'boneless skinless chicken breast','apiIngredientId'=>'1055062'],
            ['name' =>'bourbon','apiIngredientId'=>'10014037'],
            ['name' =>'brandy','apiIngredientId'=>'10114037'],
            ['name' =>'bread','apiIngredientId'=>'18064'],
            ['name' =>'bread flour','apiIngredientId'=>'10120129'],
            ['name' =>'breakfast links','apiIngredientId'=>'7919'],
            ['name' =>'brie','apiIngredientId'=>'1006'],
            ['name' =>'broccoli','apiIngredientId'=>'11090'],
            ['name' =>'broccoli florets','apiIngredientId'=>'10011090'],
            ['name' =>'brown rice','apiIngredientId'=>'20040'],
            ['name' =>'brown rice flour','apiIngredientId'=>'20090'],
            ['name' =>'brown sugar','apiIngredientId'=>'19334'],
            ['name' =>'brownie mix','apiIngredientId'=>'18632'],
            ['name' =>'brussel sprouts','apiIngredientId'=>'11098'],
            ['name' =>'bulgur','apiIngredientId'=>'20012'],
            ['name' =>'butter','apiIngredientId'=>'1001'],
            ['name' =>'butterhead lettuce','apiIngredientId'=>'11250'],
            ['name' =>'buttermilk','apiIngredientId'=>'1230'],
            ['name' =>'butternut squash','apiIngredientId'=>'11485'],
            ['name' =>'butterscotch chips','apiIngredientId'=>'19070'],
            ['name' =>'cabbage','apiIngredientId'=>'11109'],
            ['name' =>'caesar dressing','apiIngredientId'=>'43015'],
            ['name' =>'cajun seasoning','apiIngredientId'=>'1032028'],
            ['name' =>'cake flour','apiIngredientId'=>'10020129'],
            ['name' =>'candy canes','apiIngredientId'=>'93759'],
            ['name' =>'candy coating','apiIngredientId'=>'98857'],
            ['name' =>'candy melts','apiIngredientId'=>'93775'],
            ['name' =>'canned black beans','apiIngredientId'=>'16018'],
            ['name' =>'canned diced tomatoes','apiIngredientId'=>'11531'],
            ['name' =>'canned garbanzo beans','apiIngredientId'=>'16058'],
            ['name' =>'canned green chiles','apiIngredientId'=>'11980'],
            ['name' =>'canned kidney beans','apiIngredientId'=>'16034'],
            ['name' =>'canned mushrooms','apiIngredientId'=>'11264'],
            ['name' =>'canned pinto beans','apiIngredientId'=>'16044'],
            ['name' =>'canned red kidney beans','apiIngredientId'=>'10016034'],
            ['name' =>'canned tomatoes','apiIngredientId'=>'10011693'],
            ['name' =>'canned tuna','apiIngredientId'=>'10115121'],
            ['name' =>'canned white beans','apiIngredientId'=>'16051'],
            ['name' =>'canned white cannellini beans','apiIngredientId'=>'10016051'],
            ['name' =>'cannellini beans','apiIngredientId'=>'10716050'],
            ['name' =>'cantaloupe','apiIngredientId'=>'9181'],
            ['name' =>'capers','apiIngredientId'=>'2054'],
            ['name' =>'caramel sauce','apiIngredientId'=>'19364'],
            ['name' =>'caramels','apiIngredientId'=>'19074'],
            ['name' =>'caraway seed','apiIngredientId'=>'2005'],
            ['name' =>'cardamom','apiIngredientId'=>'2006'],
            ['name' =>'cardamom pods','apiIngredientId'=>'1002006'],
            ['name' =>'carp','apiIngredientId'=>'15008'],
            ['name' =>'carrots','apiIngredientId'=>'11124'],
            ['name' =>'cat fish filets','apiIngredientId'=>'15010'],
            ['name' =>'cauliflower','apiIngredientId'=>'11135'],
            ['name' =>'cauliflower florets','apiIngredientId'=>'10011135'],
            ['name' =>'cauliflower rice','apiIngredientId'=>'10111135'],
            ['name' =>'celery','apiIngredientId'=>'11143'],
            ['name' =>'celery ribs','apiIngredientId'=>'10111143'],
            ['name' =>'celery root','apiIngredientId'=>'11141'],
            ['name' =>'celery salt','apiIngredientId'=>'1052047'],
            ['name' =>'celery seed','apiIngredientId'=>'2007'],
            ['name' =>'cereal','apiIngredientId'=>'8029'],
            ['name' =>'champagne','apiIngredientId'=>'10043155'],
            ['name' =>'chana dal','apiIngredientId'=>'99236'],
            ['name' =>'cheddar','apiIngredientId'=>'1009'],
            ['name' =>'cheese','apiIngredientId'=>'1041009'],
            ['name' =>'cheese curds','apiIngredientId'=>'98921'],
            ['name' =>'cheese dip','apiIngredientId'=>'1188'],
            ['name' =>'cheese soup','apiIngredientId'=>'6038'],
            ['name' =>'cheese tortellini','apiIngredientId'=>'10093727'],
            ['name' =>'cherry','apiIngredientId'=>'9070'],
            ['name' =>'cherry pie filling','apiIngredientId'=>'19314'],
            ['name' =>'cherry tomatoes','apiIngredientId'=>'10311529'],
            ['name' =>'chestnuts','apiIngredientId'=>'12098'],
            ['name' =>'chia seeds','apiIngredientId'=>'12006'],
            ['name' =>'chicken base','apiIngredientId'=>'6080'],
            ['name' =>'chicken bouillon','apiIngredientId'=>'6480'],
            ['name' =>'chicken bouillon granules','apiIngredientId'=>'1006080'],
            ['name' =>'chicken breasts','apiIngredientId'=>'5062'],
            ['name' =>'chicken broth','apiIngredientId'=>'6194'],
            ['name' =>'chicken drumsticks','apiIngredientId'=>'5066'],
            ['name' =>'chicken legs','apiIngredientId'=>'5075'],
            ['name' =>'chicken pieces','apiIngredientId'=>'1005006'],
            ['name' =>'chicken sausage','apiIngredientId'=>'93668'],
            ['name' =>'chicken stock','apiIngredientId'=>'6172'],
            ['name' =>'chicken tenders','apiIngredientId'=>'1015062'],
            ['name' =>'chicken thighs','apiIngredientId'=>'5091'],
            ['name' =>'chicken wings','apiIngredientId'=>'5100'],
            ['name' =>'chickpea','apiIngredientId'=>'16057'],
            ['name' =>'chile garlic sauce','apiIngredientId'=>'93749'],
            ['name' =>'chili paste','apiIngredientId'=>'6973'],
            ['name' =>'chili peppers','apiIngredientId'=>'11962'],
            ['name' =>'chili powder','apiIngredientId'=>'2009'],
            ['name' =>'chili sauce','apiIngredientId'=>'6972'],
            ['name' =>'chipotle chiles in adobo','apiIngredientId'=>'11632'],
            ['name' =>'chipotle chilies','apiIngredientId'=>'98839'],
            ['name' =>'chipotle peppers in adobo','apiIngredientId'=>'99223'],
            ['name' =>'chive & onion cream cheese spread','apiIngredientId'=>'93748'],
            ['name' =>'chocolate','apiIngredientId'=>'19081'],
            ['name' =>'chocolate chip cookies','apiIngredientId'=>'28027'],
            ['name' =>'chocolate chunks','apiIngredientId'=>'10419903'],
            ['name' =>'chocolate ice cream','apiIngredientId'=>'19270'],
            ['name' =>'chocolate milk','apiIngredientId'=>'1102'],
            ['name' =>'chocolate sandwich cookies','apiIngredientId'=>'18166'],
            ['name' =>'chocolate syrup','apiIngredientId'=>'14181'],
            ['name' =>'chocolate wafer cookies','apiIngredientId'=>'10118157'],
            ['name' =>'chorizo sausage','apiIngredientId'=>'7019'],
            ['name' =>'cider vinegar','apiIngredientId'=>'2048'],
            ['name' =>'cilantro','apiIngredientId'=>'11165'],
            ['name' =>'cinnamon roll','apiIngredientId'=>'99020'],
            ['name' =>'cinnamon stick','apiIngredientId'=>'1002010'],
            ['name' =>'cinnamon sugar','apiIngredientId'=>'10219335'],
            ['name' =>'cinnamon swirl bread','apiIngredientId'=>'18047'],
            ['name' =>'clam juice','apiIngredientId'=>'14187'],
            ['name' =>'clams','apiIngredientId'=>'15157'],
            ['name' =>'clarified butter','apiIngredientId'=>'93632'],
            ['name' =>'clove','apiIngredientId'=>'1002011'],
            ['name' =>'coarse salt','apiIngredientId'=>'1002047'],
            ['name' =>'coarsely ground pepper','apiIngredientId'=>'2035'],
            ['name' =>'cocoa nibs','apiIngredientId'=>'98846'],
            ['name' =>'cocoa powder','apiIngredientId'=>'19165'],
            ['name' =>'coconut','apiIngredientId'=>'12104'],
            ['name' =>'coconut aminos','apiIngredientId'=>'98929'],
            ['name' =>'coconut butter','apiIngredientId'=>'93746'],
            ['name' =>'coconut cream','apiIngredientId'=>'12115'],
            ['name' =>'coconut extract','apiIngredientId'=>'1032050'],
            ['name' =>'coconut flour','apiIngredientId'=>'93747'],
            ['name' =>'coconut milk','apiIngredientId'=>'12118'],
            ['name' =>'coconut oil','apiIngredientId'=>'4047'],
            ['name' =>'coconut water','apiIngredientId'=>'12119'],
            ['name' =>'cod','apiIngredientId'=>'15015'],
            ['name' =>'coffee','apiIngredientId'=>'14209'],
            ['name' =>'cognac','apiIngredientId'=>'10414037'],
            ['name' =>'cola','apiIngredientId'=>'14400'],
            ['name' =>'colby jack','apiIngredientId'=>'1011'],
            ['name' =>'collard greens','apiIngredientId'=>'11161'],
            ['name' =>'condensed cream of celery soup','apiIngredientId'=>'6010'],
            ['name' =>'condensed cream of mushroom soup','apiIngredientId'=>'6147'],
            ['name' =>'confectioners swerve','apiIngredientId'=>'99084'],
            ['name' =>'cooked bacon','apiIngredientId'=>'10862'],
            ['name' =>'cooked brown rice','apiIngredientId'=>'20041'],
            ['name' =>'cooked chicken breast','apiIngredientId'=>'5064'],
            ['name' =>'cooked ham','apiIngredientId'=>'10802'],
            ['name' =>'cooked long grain rice','apiIngredientId'=>'10220445'],
            ['name' =>'cooked pasta','apiIngredientId'=>'20421'],
            ['name' =>'cooked polenta','apiIngredientId'=>'1008166'],
            ['name' =>'cooked quinoa','apiIngredientId'=>'20137'],
            ['name' =>'cooked wild rice','apiIngredientId'=>'20088'],
            ['name' =>'cookies','apiIngredientId'=>'10118192'],
            ['name' =>'coriander','apiIngredientId'=>'2012'],
            ['name' =>'corn','apiIngredientId'=>'11168'],
            ['name' =>'corn bread mix','apiIngredientId'=>'18022'],
            ['name' =>'corn chips','apiIngredientId'=>'19003'],
            ['name' =>'corn flakes cereal','apiIngredientId'=>'8020'],
            ['name' =>'corn flour','apiIngredientId'=>'20019'],
            ['name' =>'corn kernels','apiIngredientId'=>'11172'],
            ['name' =>'corn oil','apiIngredientId'=>'42289'],
            ['name' =>'corn tortillas','apiIngredientId'=>'18363'],
            ['name' =>'cornbread','apiIngredientId'=>'18023'],
            ['name' =>'corned beef','apiIngredientId'=>'13346'],
            ['name' =>'cornish hens','apiIngredientId'=>'5307'],
            ['name' =>'cornmeal','apiIngredientId'=>'35137'],
            ['name' =>'cornstarch','apiIngredientId'=>'20027'],
            ['name' =>'cotija cheese','apiIngredientId'=>'1001019'],
            ['name' =>'cottage cheese','apiIngredientId'=>'1012'],
            ['name' =>'country bread','apiIngredientId'=>'10018029'],
            ['name' =>'courgettes','apiIngredientId'=>'11477'],
            ['name' =>'couscous','apiIngredientId'=>'20028'],
            ['name' =>'cow pea','apiIngredientId'=>'16063'],
            ['name' =>'crabmeat','apiIngredientId'=>'10015136'],
            ['name' =>'cracked pepper','apiIngredientId'=>'2030'],
            ['name' =>'cranberries','apiIngredientId'=>'9078'],
            ['name' =>'cranberry juice','apiIngredientId'=>'43382'],
            ['name' =>'cream','apiIngredientId'=>'1053'],
            ['name' =>'cream cheese','apiIngredientId'=>'1017'],
            ['name' =>'cream cheese block','apiIngredientId'=>'1186'],
            ['name' =>'cream of chicken soup','apiIngredientId'=>'6016'],
            ['name' =>'cream of tartar','apiIngredientId'=>'18373'],
            ['name' =>'creamed corn','apiIngredientId'=>'11174'],
            ['name' =>'creamy peanut butter','apiIngredientId'=>'10116098'],
            ['name' =>'creme fraiche','apiIngredientId'=>'1001056'],
            ['name' =>'cremini mushrooms','apiIngredientId'=>'11266'],
            ['name' =>'creole seasoning','apiIngredientId'=>'1002031'],
            ['name' =>'crisp rice cereal','apiIngredientId'=>'8066'],
            ['name' =>'croutons','apiIngredientId'=>'18242'],
            ['name' =>'crystallized ginger','apiIngredientId'=>'93751'],
            ['name' =>'cucumber','apiIngredientId'=>'11206'],
            ['name' =>'cumin seeds','apiIngredientId'=>'2014'],
            ['name' =>'cup cake','apiIngredientId'=>'18139'],
            ['name' =>'currants','apiIngredientId'=>'9085'],
            ['name' =>'curry leaves','apiIngredientId'=>'93604'],
            ['name' =>'dairy free milk','apiIngredientId'=>'10016223'],
            ['name' =>'dark brown sugar','apiIngredientId'=>'10019334'],
            ['name' =>'dark chocolate','apiIngredientId'=>'19904'],
            ['name' =>'dark chocolate candy bars','apiIngredientId'=>'10019904'],
            ['name' =>'dark chocolate chips','apiIngredientId'=>'10019071'],
            ['name' =>'dark sesame oil','apiIngredientId'=>'1004058'],
            ['name' =>'dates','apiIngredientId'=>'9087'],
            ['name' =>'deep dish pie crust','apiIngredientId'=>'18945'],
            ['name' =>'deli ham','apiIngredientId'=>'10010151'],
            ['name' =>'deli turkey','apiIngredientId'=>'7259'],
            ['name' =>'dessert oats','apiIngredientId'=>'8121'],
            ['name' =>'dessert wine','apiIngredientId'=>'10014057'],
            ['name' =>'diced ham','apiIngredientId'=>'99186'],
            ['name' =>'diet pop','apiIngredientId'=>'14146'],
            ['name' =>'dijon mustard','apiIngredientId'=>'1002046'],
            ['name' =>'dill','apiIngredientId'=>'2045'],
            ['name' =>'dill pickles','apiIngredientId'=>'10011937'],
            ['name' =>'hot dog','apiIngredientId'=>'21118'],
            ['name' =>'double cream','apiIngredientId'=>'1011053'],
            ['name' =>'dried apricots','apiIngredientId'=>'9032'],
            ['name' =>'dried basil','apiIngredientId'=>'2003'],
            ['name' =>'dried cherries','apiIngredientId'=>'93822'],
            ['name' =>'dried chorizo','apiIngredientId'=>'99233'],
            ['name' =>'dried cranberries','apiIngredientId'=>'9079'],
            ['name' =>'dried dill','apiIngredientId'=>'2017'],
            ['name' =>'dried onion','apiIngredientId'=>'11284'],
            ['name' =>'dried porcini mushrooms','apiIngredientId'=>'10011268'],
            ['name' =>'dried rubbed sage','apiIngredientId'=>'1002038'],
            ['name' =>'dried thyme','apiIngredientId'=>'2042'],
            ['name' =>'dried tomatoes','apiIngredientId'=>'11955'],
            ['name' =>'dry bread crumbs','apiIngredientId'=>'18079'],
            ['name' =>'dry milk','apiIngredientId'=>'1090'],
            ['name' =>'dry mustard','apiIngredientId'=>'1002024'],
            ['name' =>'dry red wine','apiIngredientId'=>'14097'],
            ['name' =>'dry roasted peanuts','apiIngredientId'=>'16090'],
            ['name' =>'duck fat','apiIngredientId'=>'4574'],
            ['name' =>'dutch process cocoa powder','apiIngredientId'=>'10019165'],
            ['name' =>'edamame','apiIngredientId'=>'11212'],
            ['name' =>'egg substitute','apiIngredientId'=>'1226'],
            ['name' =>'egg vermicelli','apiIngredientId'=>'20409'],
            ['name' =>'egg whites','apiIngredientId'=>'1124'],
            ['name' =>'egg yolk','apiIngredientId'=>'1125'],
            ['name' =>'eggnog','apiIngredientId'=>'1057'],
            ['name' =>'eggplant','apiIngredientId'=>'11209'],
            ['name' =>'elbow macaroni','apiIngredientId'=>'10120499'],
            ['name' =>'enchilada sauce','apiIngredientId'=>'6599'],
            ['name' =>'english cucumber','apiIngredientId'=>'10111205'],
            ['name' =>'english muffin','apiIngredientId'=>'18439'],
            ['name' =>'erythritol','apiIngredientId'=>'98887'],
            ['name' =>'escarole','apiIngredientId'=>'11213'],
            ['name' =>'espresso','apiIngredientId'=>'14210'],
            ['name' =>'evaporated milk','apiIngredientId'=>'1214'],
            ['name' =>'extra firm tofu','apiIngredientId'=>'16163'],
            ['name' =>'extra virgin olive oil','apiIngredientId'=>'1034053'],
            ['name' =>'farfalle','apiIngredientId'=>'10120420'],
            ['name' =>'farro','apiIngredientId'=>'10020005'],
            ['name' =>'fat free mayo','apiIngredientId'=>'42193'],
            ['name' =>'fat-free less-sodium chicken broth','apiIngredientId'=>'6984'],
            ['name' =>'fennel','apiIngredientId'=>'11957'],
            ['name' =>'fennel seeds','apiIngredientId'=>'2018'],
            ['name' =>'fenugreek leaf','apiIngredientId'=>'98963'],
            ['name' =>'fenugreek seeds','apiIngredientId'=>'2019'],
            ['name' =>'feta cheese','apiIngredientId'=>'1019'],
            ['name' =>'fettuccine','apiIngredientId'=>'10020409'],
            ['name' =>'fire roasted tomatoes','apiIngredientId'=>'98849'],
            ['name' =>'fish','apiIngredientId'=>'10115261'],
            ['name' =>'fish sauce','apiIngredientId'=>'6179'],
            ['name' =>'fish stock','apiIngredientId'=>'6963'],
            ['name' =>'flank steak','apiIngredientId'=>'23657'],
            ['name' =>'flax seeds','apiIngredientId'=>'10012220'],
            ['name' =>'fleur de sel','apiIngredientId'=>'1022047'],
            ['name' =>'flour','apiIngredientId'=>'20081'],
            ['name' =>'flour tortillas','apiIngredientId'=>'10218364'],
            ['name' =>'fontina cheese','apiIngredientId'=>'1020'],
            ['name' =>'food dye','apiIngredientId'=>'10711111'],
            ['name' =>'franks redhot sauce','apiIngredientId'=>'98878'],
            ['name' =>'free range eggs','apiIngredientId'=>'1123'],
            ['name' =>'french bread','apiIngredientId'=>'18029'],
            ['name' =>'fresh basil','apiIngredientId'=>'2044'],
            ['name' =>'fresh bean sprouts','apiIngredientId'=>'11043'],
            ['name' =>'fresh chives','apiIngredientId'=>'11156'],
            ['name' =>'fresh corn','apiIngredientId'=>'11167'],
            ['name' =>'fresh corn kernels','apiIngredientId'=>'10011167'],
            ['name' =>'fresh figs','apiIngredientId'=>'9089'],
            ['name' =>'fresh fruit','apiIngredientId'=>'9431'],
            ['name' =>'fresh herbs','apiIngredientId'=>'10111297'],
            ['name' =>'fresh mint','apiIngredientId'=>'2064'],
            ['name' =>'fresh mozzarella','apiIngredientId'=>'1026'],
            ['name' =>'fresh rosemary','apiIngredientId'=>'2063'],
            ['name' =>'fresh thyme leaves','apiIngredientId'=>'2049'],
            ['name' =>'fried onions','apiIngredientId'=>'93709'],
            ['name' =>'frosting','apiIngredientId'=>'19230'],
            ['name' =>'froyo bars','apiIngredientId'=>'93629'],
            ['name' =>'frozen corn','apiIngredientId'=>'11913'],
            ['name' =>'frozen spinach','apiIngredientId'=>'11463'],
            ['name' =>'fudge','apiIngredientId'=>'19100'],
            ['name' =>'fudge topping','apiIngredientId'=>'10019348'],
            ['name' =>'fun size almond joy bar','apiIngredientId'=>'19065'],
            ['name' =>'garam masala','apiIngredientId'=>'93663'],
            ['name' =>'garbanzo bean flour','apiIngredientId'=>'16157'],
            ['name' =>'garlic','apiIngredientId'=>'11215'],
            ['name' =>'garlic paste','apiIngredientId'=>'10111215'],
            ['name' =>'garlic powder','apiIngredientId'=>'1022020'],
            ['name' =>'garlic powder','apiIngredientId'=>'2020'],
            ['name' =>'garlic salt','apiIngredientId'=>'1062047'],
            ['name' =>'gelatin','apiIngredientId'=>'19177'],
            ['name' =>'gf chocolate cake mix','apiIngredientId'=>'99040'],
            ['name' =>'gin','apiIngredientId'=>'10514037'],
            ['name' =>'ginger','apiIngredientId'=>'11216'],
            ['name' =>'ginger ale','apiIngredientId'=>'14136'],
            ['name' =>'ginger paste','apiIngredientId'=>'93754'],
            ['name' =>'ginger-garlic paste','apiIngredientId'=>'10093754'],
            ['name' =>'gingersnap cookies','apiIngredientId'=>'18172'],
            ['name' =>'gnocchi','apiIngredientId'=>'98853'],
            ['name' =>'goat cheese','apiIngredientId'=>'1159'],
            ['name' =>'golden raisins','apiIngredientId'=>'9297'],
            ['name' =>'gorgonzola','apiIngredientId'=>'1011004'],
            ['name' =>'gouda cheese','apiIngredientId'=>'1022'],
            ['name' =>'graham cracker crumbs','apiIngredientId'=>'10018617'],
            ['name' =>'graham cracker pie crust','apiIngredientId'=>'18942'],
            ['name' =>'graham crackers','apiIngredientId'=>'18617'],
            ['name' =>'grain blend','apiIngredientId'=>'10020088'],
            ['name' =>'grand marnier','apiIngredientId'=>'10314534'],
            ['name' =>'granny smith apples','apiIngredientId'=>'1089003'],
            ['name' =>'granola','apiIngredientId'=>'8212'],
            ['name' =>'granulated garlic','apiIngredientId'=>'1002020'],
            ['name' =>'grape tomatoes','apiIngredientId'=>'10111529'],
            ['name' =>'grapefruit','apiIngredientId'=>'9112'],
            ['name' =>'grapeseed oil','apiIngredientId'=>'4517'],
            ['name' =>'gravy','apiIngredientId'=>'6997'],
            ['name' =>'great northern beans','apiIngredientId'=>'16025'],
            ['name' =>'greek yogurt','apiIngredientId'=>'1256'],
            ['name' =>'green beans','apiIngredientId'=>'11052'],
            ['name' =>'green bell pepper','apiIngredientId'=>'11333'],
            ['name' =>'green chili pepper','apiIngredientId'=>'31015'],
            ['name' =>'green food coloring','apiIngredientId'=>'1441111'],
            ['name' =>'green grapes','apiIngredientId'=>'1019132'],
            ['name' =>'green olives','apiIngredientId'=>'1029195'],
            ['name' =>'green onions','apiIngredientId'=>'11291'],
            ['name' =>'greens','apiIngredientId'=>'21052'],
            ['name' =>'grill cheese','apiIngredientId'=>'10093624'],
            ['name' =>'grill seasoning','apiIngredientId'=>'1022034'],
            ['name' =>'ground allspice','apiIngredientId'=>'2001'],
            ['name' =>'ground ancho chili','apiIngredientId'=>'1022009'],
            ['name' =>'ground beef','apiIngredientId'=>'10023572'],
            ['name' =>'ground chicken','apiIngredientId'=>'5332'],
            ['name' =>'ground chipotle chile pepper','apiIngredientId'=>'1052009'],
            ['name' =>'ground cinnamon','apiIngredientId'=>'1012010'],
            ['name' =>'ground cinnamon','apiIngredientId'=>'2010'],
            ['name' =>'ground cloves','apiIngredientId'=>'2011'],
            ['name' =>'ground coriander seeds','apiIngredientId'=>'1002013'],
            ['name' =>'ground cumin','apiIngredientId'=>'1002014'],
            ['name' =>'ground flaxseed','apiIngredientId'=>'12220'],
            ['name' =>'ground ginger','apiIngredientId'=>'2021'],
            ['name' =>'ground lamb','apiIngredientId'=>'17224'],
            ['name' =>'ground mace','apiIngredientId'=>'2022'],
            ['name' =>'ground nutmeg','apiIngredientId'=>'2025'],
            ['name' =>'ground pork','apiIngredientId'=>'10219'],
            ['name' =>'ground pork sausage','apiIngredientId'=>'7063'],
            ['name' =>'ground veal','apiIngredientId'=>'17142'],
            ['name' =>'gruyere','apiIngredientId'=>'1023'],
            ['name' =>'guacamole','apiIngredientId'=>'1009037'],
            ['name' =>'half n half','apiIngredientId'=>'1049'],
            ['name' =>'halibut fillet','apiIngredientId'=>'15036'],
            ['name' =>'ham','apiIngredientId'=>'10151'],
            ['name' =>'hamburger buns','apiIngredientId'=>'18350'],
            ['name' =>'hard cooked eggs','apiIngredientId'=>'1129'],
            ['name' =>'harissa','apiIngredientId'=>'1006972'],
            ['name' =>'hash brown potatoes','apiIngredientId'=>'11390'],
            ['name' =>'hazelnuts','apiIngredientId'=>'12120'],
            ['name' =>'healthy request cream of celery soup','apiIngredientId'=>'6987'],
            ['name' =>'hemp seeds','apiIngredientId'=>'93602'],
            ['name' =>'herbes de provence','apiIngredientId'=>'1012042'],
            ['name' =>'herbs','apiIngredientId'=>'1002044'],
            ['name' =>'hersheys kisses brand milk chocolates','apiIngredientId'=>'93743'],
            ['name' =>'hoisin sauce','apiIngredientId'=>'6175'],
            ['name' =>'honey mustard','apiIngredientId'=>'99227'],
            ['name' =>'horseradish','apiIngredientId'=>'1002055'],
            ['name' =>'hot sauce','apiIngredientId'=>'6168'],
            ['name' =>'hummus','apiIngredientId'=>'16158'],
            ['name' =>'ice','apiIngredientId'=>'10014412'],
            ['name' =>'ice cream','apiIngredientId'=>'19095'],
            ['name' =>'instant chocolate pudding mix','apiIngredientId'=>'19184'],
            ['name' =>'instant coffee powder','apiIngredientId'=>'14214'],
            ['name' =>'instant espresso powder','apiIngredientId'=>'10014214'],
            ['name' =>'instant lemon pudding mix','apiIngredientId'=>'19332'],
            ['name' =>'instant yeast','apiIngredientId'=>'10118375'],
            ['name' =>'irish cream','apiIngredientId'=>'93764'],
            ['name' =>'italian bread','apiIngredientId'=>'10028033'],
            ['name' =>'italian cheese blend','apiIngredientId'=>'93651'],
            ['name' =>'italian sausages','apiIngredientId'=>'7036'],
            ['name' =>'italian seasoning','apiIngredientId'=>'1022027'],
            ['name' =>'jaggery','apiIngredientId'=>'99002'],
            ['name' =>'jalapeno','apiIngredientId'=>'11979'],
            ['name' =>'jasmine rice','apiIngredientId'=>'10120444'],
            ['name' =>'jelly','apiIngredientId'=>'19297'],
            ['name' =>'jicama','apiIngredientId'=>'11603'],
            ['name' =>'jimmies','apiIngredientId'=>'93645'],
            ['name' =>'juice','apiIngredientId'=>'1019016'],
            ['name' =>'jumbo shell pasta','apiIngredientId'=>'10520420'],
            ['name' =>'kaffir lime leaves','apiIngredientId'=>'93633'],
            ['name' =>'kahlua','apiIngredientId'=>'93716'],
            ['name' =>'kalamata olives','apiIngredientId'=>'1009195'],
            ['name' =>'kale','apiIngredientId'=>'11233'],
            ['name' =>'ketchup','apiIngredientId'=>'11935'],
            ['name' =>'kitchen bouquet','apiIngredientId'=>'93768'],
            ['name' =>'kiwis','apiIngredientId'=>'9148'],
            ['name' =>'kosher salt','apiIngredientId'=>'1082047'],
            ['name' =>'ladyfingers','apiIngredientId'=>'18423'],
            ['name' =>'lamb','apiIngredientId'=>'10017224'],
            ['name' =>'lasagna noodles','apiIngredientId'=>'10620420'],
            ['name' =>'lb cake','apiIngredientId'=>'18133'],
            ['name' =>'lean ground beef','apiIngredientId'=>'23557'],
            ['name' =>'lean ground turkey','apiIngredientId'=>'5662'],
            ['name' =>'lean pork tenderloin','apiIngredientId'=>'10060'],
            ['name' =>'leeks','apiIngredientId'=>'11246'],
            ['name' =>'leg of lamb','apiIngredientId'=>'17013'],
            ['name' =>'lemon','apiIngredientId'=>'9150'],
            ['name' =>'lemon curd','apiIngredientId'=>'93834'],
            ['name' =>'lemon extract','apiIngredientId'=>'12311111'],
            ['name' =>'lemon juice','apiIngredientId'=>'9152'],
            ['name' =>'lemon peel','apiIngredientId'=>'9156'],
            ['name' =>'lemon pepper','apiIngredientId'=>'1012030'],
            ['name' =>'lemon wedges','apiIngredientId'=>'1029150'],
            ['name' =>'lemongrass','apiIngredientId'=>'11972'],
            ['name' =>'lettuce','apiIngredientId'=>'11252'],
            ['name' =>'lettuce leaves','apiIngredientId'=>'93623'],
            ['name' =>'light butter','apiIngredientId'=>'4602'],
            ['name' =>'light coconut milk','apiIngredientId'=>'99009'],
            ['name' =>'light corn syrup','apiIngredientId'=>'19350'],
            ['name' =>'light cream cheese','apiIngredientId'=>'43274'],
            ['name' =>'light mayonnaise','apiIngredientId'=>'4641'],
            ['name' =>'light olive oil','apiIngredientId'=>'1054053'],
            ['name' =>'light soy sauce','apiIngredientId'=>'10216124'],
            ['name' =>'lime','apiIngredientId'=>'9159'],
            ['name' =>'lime juice','apiIngredientId'=>'9160'],
            ['name' =>'lime wedges','apiIngredientId'=>'1029159'],
            ['name' =>'lime zest','apiIngredientId'=>'1009159'],
            ['name' =>'linguine','apiIngredientId'=>'10720420'],
            ['name' =>'liquid smoke','apiIngredientId'=>'93627'],
            ['name' =>'liquid stevia','apiIngredientId'=>'10811111'],
            ['name' =>'liquor','apiIngredientId'=>'14037'],
            ['name' =>'live lobster','apiIngredientId'=>'15147'],
            ['name' =>'long-grain rice','apiIngredientId'=>'10220444'],
            ['name' =>'low fat buttermilk','apiIngredientId'=>'1088'],
            ['name' =>'low fat milk','apiIngredientId'=>'1082'],
            ['name' =>'low fat milk','apiIngredientId'=>'1174'],
            ['name' =>'low fat plain yogurt','apiIngredientId'=>'1117'],
            ['name' =>'low fat ricotta cheese','apiIngredientId'=>'1037'],
            ['name' =>'low fat sour cream','apiIngredientId'=>'1179'],
            ['name' =>'low sodium chicken broth','apiIngredientId'=>'6970'],
            ['name' =>'low sodium soy sauce','apiIngredientId'=>'16424'],
            ['name' =>'low-sodium chicken stock','apiIngredientId'=>'1006970'],
            ['name' =>'lower sodium beef broth','apiIngredientId'=>'10093741'],
            ['name' =>'lump crab','apiIngredientId'=>'10115136'],
            ['name' =>'m&m candies','apiIngredientId'=>'19157'],
            ['name' =>'macadamia nuts','apiIngredientId'=>'12131'],
            ['name' =>'macaroni and cheese mix','apiIngredientId'=>'32004'],
            ['name' =>'madras curry powder','apiIngredientId'=>'2015'],
            ['name' =>'malt drink mix','apiIngredientId'=>'14311'],
            ['name' =>'mandarin orange sections','apiIngredientId'=>'9383'],
            ['name' =>'mandarin oranges','apiIngredientId'=>'9218'],
            ['name' =>'mango','apiIngredientId'=>'9176'],
            ['name' =>'maple syrup','apiIngredientId'=>'19911'],
            ['name' =>'maraschino cherries','apiIngredientId'=>'9328'],
            ['name' =>'margarine','apiIngredientId'=>'4073'],
            ['name' =>'marinara sauce','apiIngredientId'=>'10111549'],
            ['name' =>'marjoram','apiIngredientId'=>'2023'],
            ['name' =>'marsala wine','apiIngredientId'=>'14057'],
            ['name' =>'marshmallow fluff','apiIngredientId'=>'93644'],
            ['name' =>'marshmallows','apiIngredientId'=>'19116'],
            ['name' =>'masa harina','apiIngredientId'=>'20317'],
            ['name' =>'mascarpone','apiIngredientId'=>'93820'],
            ['name' =>'mat beans','apiIngredientId'=>'99144'],
            ['name' =>'matcha tea','apiIngredientId'=>'98932'],
            ['name' =>'mayonnaise','apiIngredientId'=>'4025'],
            ['name' =>'meat','apiIngredientId'=>'1015006'],
            ['name' =>'meat','apiIngredientId'=>'1065062'],
            ['name' =>'meatballs','apiIngredientId'=>'10110219'],
            ['name' =>'medjool dates','apiIngredientId'=>'9421'],
            ['name' =>'mexican cream','apiIngredientId'=>'93772'],
            ['name' =>'meyer lemon juice','apiIngredientId'=>'1009152'],
            ['name' =>'milk','apiIngredientId'=>'1077'],
            ['name' =>'milk chocolate chips','apiIngredientId'=>'10019146'],
            ['name' =>'mint chutney','apiIngredientId'=>'98991'],
            ['name' =>'minute rice','apiIngredientId'=>'20048'],
            ['name' =>'miracle whip','apiIngredientId'=>'4014'],
            ['name' =>'mirin','apiIngredientId'=>'93830'],
            ['name' =>'miso','apiIngredientId'=>'16112'],
            ['name' =>'molasses','apiIngredientId'=>'19304'],
            ['name' =>'monterey jack cheese','apiIngredientId'=>'1001025'],
            ['name' =>'mushroom','apiIngredientId'=>'11260'],
            ['name' =>'mussels','apiIngredientId'=>'15164'],
            ['name' =>'mustard','apiIngredientId'=>'2046'],
            ['name' =>'mustard seeds','apiIngredientId'=>'2024'],
            ['name' =>'napa cabbage','apiIngredientId'=>'11119'],
            ['name' =>'navel oranges','apiIngredientId'=>'9202'],
            ['name' =>'nectarine','apiIngredientId'=>'9191'],
            ['name' =>'new potatoes','apiIngredientId'=>'11352'],
            ['name' =>'non-fat greek yogurt','apiIngredientId'=>'1011256'],
            ['name' =>'nonfat cool whip','apiIngredientId'=>'1200'],
            ['name' =>'nonfat milk','apiIngredientId'=>'1085'],
            ['name' =>'nori','apiIngredientId'=>'11446'],
            ['name' =>'nut butter','apiIngredientId'=>'12195'],
            ['name' =>'nut meal','apiIngredientId'=>'93620'],
            ['name' =>'nutella','apiIngredientId'=>'19125'],
            ['name' =>'nutritional yeast','apiIngredientId'=>'93690'],
            ['name' =>'oat flour','apiIngredientId'=>'20132'],
            ['name' =>'oats','apiIngredientId'=>'8120'],
            ['name' =>'oil','apiIngredientId'=>'4582'],
            ['name' =>'oil packed sun dried tomatoes','apiIngredientId'=>'11956'],
            ['name' =>'okra','apiIngredientId'=>'11278'],
            ['name' =>'old bay seasoning','apiIngredientId'=>'1052034'],
            ['name' =>'olive oil','apiIngredientId'=>'4053'],
            ['name' =>'olives','apiIngredientId'=>'9195'],
            ['name' =>'onion','apiIngredientId'=>'11282'],
            ['name' =>'onion powder','apiIngredientId'=>'2026'],
            ['name' =>'onion soup mix','apiIngredientId'=>'6094'],
            ['name' =>'orange','apiIngredientId'=>'9200'],
            ['name' =>'orange bell pepper','apiIngredientId'=>'10011821'],
            ['name' =>'orange juice','apiIngredientId'=>'9206'],
            ['name' =>'orange juice concentrate','apiIngredientId'=>'9214'],
            ['name' =>'orange liqueur','apiIngredientId'=>'10414534'],
            ['name' =>'orange marmalade','apiIngredientId'=>'19303'],
            ['name' =>'orange oil','apiIngredientId'=>'12511111'],
            ['name' =>'orange zest','apiIngredientId'=>'9216'],
            ['name' =>'oregano','apiIngredientId'=>'2027'],
            ['name' =>'oreo cookies','apiIngredientId'=>'10018166'],
            ['name' =>'orzo','apiIngredientId'=>'10920420'],
            ['name' =>'oyster sauce','apiIngredientId'=>'6176'],
            ['name' =>'oysters','apiIngredientId'=>'15167'],
            ['name' =>'palm sugar','apiIngredientId'=>'93831'],
            ['name' =>'pancetta','apiIngredientId'=>'10410123'],
            ['name' =>'paneer','apiIngredientId'=>'98847'],
            ['name' =>'panko','apiIngredientId'=>'10018079'],
            ['name' =>'papaya','apiIngredientId'=>'9226'],
            ['name' =>'paprika','apiIngredientId'=>'2028'],
            ['name' =>'parmigiano reggiano','apiIngredientId'=>'1033'],
            ['name' =>'parsley','apiIngredientId'=>'11297'],
            ['name' =>'parsley flakes','apiIngredientId'=>'2029'],
            ['name' =>'parsnip','apiIngredientId'=>'11298'],
            ['name' =>'part-skim mozzarella cheese','apiIngredientId'=>'1028'],
            ['name' =>'pasta','apiIngredientId'=>'20420'],
            ['name' =>'pasta salad mix','apiIngredientId'=>'99036'],
            ['name' =>'pasta sauce','apiIngredientId'=>'10011549'],
            ['name' =>'pastry flour','apiIngredientId'=>'10020080'],
            ['name' =>'peach','apiIngredientId'=>'9236'],
            ['name' =>'peanut butter','apiIngredientId'=>'16098'],
            ['name' =>'peanut butter chips','apiIngredientId'=>'93762'],
            ['name' =>'peanut butter cups','apiIngredientId'=>'19150'],
            ['name' =>'peanut oil','apiIngredientId'=>'4042'],
            ['name' =>'peanuts','apiIngredientId'=>'16091'],
            ['name' =>'pear liqueur','apiIngredientId'=>'98988'],
            ['name' =>'pearl barley','apiIngredientId'=>'20005'],
            ['name' =>'pearl onions','apiIngredientId'=>'10111282'],
            ['name' =>'peas','apiIngredientId'=>'11304'],
            ['name' =>'pecan','apiIngredientId'=>'12142'],
            ['name' =>'pecan pieces','apiIngredientId'=>'10012142'],
            ['name' =>'pecorino','apiIngredientId'=>'1038'],
            ['name' =>'penne','apiIngredientId'=>'11120420'],
            ['name' =>'peperoncino','apiIngredientId'=>'11976'],
            ['name' =>'pepper jack cheese','apiIngredientId'=>'1025'],
            ['name' =>'peppercorns','apiIngredientId'=>'1022030'],
            ['name' =>'peppermint baking chips','apiIngredientId'=>'98858'],
            ['name' =>'peppermint extract','apiIngredientId'=>'1022050'],
            ['name' =>'pepperoni','apiIngredientId'=>'7057'],
            ['name' =>'peppers','apiIngredientId'=>'10111333'],
            ['name' =>'pesto','apiIngredientId'=>'93698'],
            ['name' =>'pickle relish','apiIngredientId'=>'11944'],
            ['name' =>'pickles','apiIngredientId'=>'11937'],
            ['name' =>'pico de gallo','apiIngredientId'=>'27027'],
            ['name' =>'pie crust','apiIngredientId'=>'18334'],
            ['name' =>'pimento stuffed olives','apiIngredientId'=>'1049195'],
            ['name' =>'pimientos','apiIngredientId'=>'11943'],
            ['name' =>'pine nuts','apiIngredientId'=>'12147'],
            ['name' =>'pineapple','apiIngredientId'=>'9266'],
            ['name' =>'pineapple chunks','apiIngredientId'=>'1029354'],
            ['name' =>'pineapple in juice','apiIngredientId'=>'9354'],
            ['name' =>'pineapple juice','apiIngredientId'=>'9273'],
            ['name' =>'pink himalayan salt','apiIngredientId'=>'1032047'],
            ['name' =>'pinto beans','apiIngredientId'=>'16043'],
            ['name' =>'pistachios','apiIngredientId'=>'12151'],
            ['name' =>'pita','apiIngredientId'=>'18413'],
            ['name' =>'pizza crust','apiIngredientId'=>'93770'],
            ['name' =>'pizza mix','apiIngredientId'=>'98924'],
            ['name' =>'plain greek yogurt','apiIngredientId'=>'1001256'],
            ['name' =>'plain nonfat yogurt','apiIngredientId'=>'1118'],
            ['name' =>'plain yogurt','apiIngredientId'=>'1001116'],
            ['name' =>'plantain','apiIngredientId'=>'9277'],
            ['name' =>'plum','apiIngredientId'=>'9279'],
            ['name' =>'plum tomatoes','apiIngredientId'=>'10411529'],
            ['name' =>'poblano peppers','apiIngredientId'=>'10011333'],
            ['name' =>'polenta','apiIngredientId'=>'10035137'],
            ['name' =>'polish sausage','apiIngredientId'=>'7059'],
            ['name' =>'pomegranate juice','apiIngredientId'=>'9442'],
            ['name' =>'pomegranate molasses','apiIngredientId'=>'10042040'],
            ['name' =>'pomegranate seeds','apiIngredientId'=>'9286'],
            ['name' =>'popcorn','apiIngredientId'=>'19034'],
            ['name' =>'poppy seeds','apiIngredientId'=>'2033'],
            ['name' =>'pork','apiIngredientId'=>'10010219'],
            ['name' =>'Pork & Beans','apiIngredientId'=>'16009'],
            ['name' =>'pork belly','apiIngredientId'=>'10005'],
            ['name' =>'pork butt','apiIngredientId'=>'10084'],
            ['name' =>'pork chops','apiIngredientId'=>'10010062'],
            ['name' =>'pork links','apiIngredientId'=>'1007063'],
            ['name' =>'pork loin chops','apiIngredientId'=>'10062'],
            ['name' =>'pork loin roast','apiIngredientId'=>'10225'],
            ['name' =>'pork roast','apiIngredientId'=>'10010225'],
            ['name' =>'pork shoulder','apiIngredientId'=>'10072'],
            ['name' =>'pork tenderloin','apiIngredientId'=>'10218'],
            ['name' =>'port','apiIngredientId'=>'10114057'],
            ['name' =>'portabella mushrooms','apiIngredientId'=>'11265'],
            ['name' =>'pot roast','apiIngredientId'=>'23612'],
            ['name' =>'potato chips','apiIngredientId'=>'19411'],
            ['name' =>'potato starch','apiIngredientId'=>'11413'],
            ['name' =>'potatoes','apiIngredientId'=>'11362'],
            ['name' =>'poultry seasoning','apiIngredientId'=>'2034'],
            ['name' =>'powdered sugar','apiIngredientId'=>'19336'],
            ['name' =>'pretzel sandwiches','apiIngredientId'=>'19047'],
            ['name' =>'processed american cheese','apiIngredientId'=>'1253'],
            ['name' =>'prosciutto','apiIngredientId'=>'10010123'],
            ['name' =>'provolone cheese','apiIngredientId'=>'1035'],
            ['name' =>'prunes','apiIngredientId'=>'9291'],
            ['name' =>'puff pastry','apiIngredientId'=>'18337'],
            ['name' =>'pumpkin','apiIngredientId'=>'11422'],
            ['name' =>'pumpkin pie filling','apiIngredientId'=>'11426'],
            ['name' =>'pumpkin pie spice','apiIngredientId'=>'1002035'],
            ['name' =>'pumpkin puree','apiIngredientId'=>'11424'],
            ['name' =>'pumpkin seeds','apiIngredientId'=>'12014'],
            ['name' =>'queso fresco','apiIngredientId'=>'1228'],
            ['name' =>'quick cooking oats','apiIngredientId'=>'8402'],
            ['name' =>'quinoa','apiIngredientId'=>'20035'],
            ['name' =>'quinoa flour','apiIngredientId'=>'93773'],
            ['name' =>'radicchio','apiIngredientId'=>'11952'],
            ['name' =>'radishes','apiIngredientId'=>'11429'],
            ['name' =>'raisins','apiIngredientId'=>'9299'],
            ['name' =>'rajma masala','apiIngredientId'=>'10193663'],
            ['name' =>'ramen noodles','apiIngredientId'=>'6583'],
            ['name' =>'ranch dressing','apiIngredientId'=>'4639'],
            ['name' =>'ranch dressing mix','apiIngredientId'=>'93733'],
            ['name' =>'raspberries','apiIngredientId'=>'9302'],
            ['name' =>'raspberry jam','apiIngredientId'=>'10719297'],
            ['name' =>'raw cashews','apiIngredientId'=>'12087'],
            ['name' =>'raw shrimp','apiIngredientId'=>'15152'],
            ['name' =>'ready-to-serve Asian fried rice','apiIngredientId'=>'93721'],
            ['name' =>'real bacon recipe pieces','apiIngredientId'=>'99229'],
            ['name' =>'red apples','apiIngredientId'=>'1079003'],
            ['name' =>'red bell peppers','apiIngredientId'=>'11821'],
            ['name' =>'red cabbage','apiIngredientId'=>'11112'],
            ['name' =>'red chilli','apiIngredientId'=>'11819'],
            ['name' =>'red delicious apples','apiIngredientId'=>'1059003'],
            ['name' =>'red food coloring','apiIngredientId'=>'1451111'],
            ['name' =>'red grapefruit juice','apiIngredientId'=>'98926'],
            ['name' =>'red grapes','apiIngredientId'=>'9132'],
            ['name' =>'red kidney beans','apiIngredientId'=>'16033'],
            ['name' =>'red lentils','apiIngredientId'=>'10016069'],
            ['name' =>'red onion','apiIngredientId'=>'10011282'],
            ['name' =>'red pepper flakes','apiIngredientId'=>'1032009'],
            ['name' =>'red pepper powder','apiIngredientId'=>'2031'],
            ['name' =>'red potatoes','apiIngredientId'=>'10011355'],
            ['name' =>'red velvet cookie','apiIngredientId'=>'18157'],
            ['name' =>'red wine','apiIngredientId'=>'14096'],
            ['name' =>'red wine vinegar','apiIngredientId'=>'1022068'],
            ['name' =>'reduced fat shredded cheddar cheese','apiIngredientId'=>'1001168'],
            ['name' =>'refried beans','apiIngredientId'=>'16202'],
            ['name' =>'refrigerated crescent rolls','apiIngredientId'=>'93618'],
            ['name' =>'refrigerated pizza dough','apiIngredientId'=>'93610'],
            ['name' =>'refrigerated sugar cookie dough','apiIngredientId'=>'18205'],
            ['name' =>'rhubarb','apiIngredientId'=>'9307'],
            ['name' =>'rib tips','apiIngredientId'=>'98937'],
            ['name' =>'rice','apiIngredientId'=>'20444'],
            ['name' =>'rice flour','apiIngredientId'=>'20061'],
            ['name' =>'rice krispies cereal','apiIngredientId'=>'8065'],
            ['name' =>'rice milk','apiIngredientId'=>'93761'],
            ['name' =>'rice noodles','apiIngredientId'=>'20133'],
            ['name' =>'rice paper','apiIngredientId'=>'10118368'],
            ['name' =>'rice syrup','apiIngredientId'=>'93784'],
            ['name' =>'rice vinegar','apiIngredientId'=>'1022053'],
            ['name' =>'rice wine','apiIngredientId'=>'43479'],
            ['name' =>'ricotta salata','apiIngredientId'=>'1036'],
            ['name' =>'ritz crackers','apiIngredientId'=>'18621'],
            ['name' =>'roast beef','apiIngredientId'=>'93713'],
            ['name' =>'roasted chicken','apiIngredientId'=>'5114'],
            ['name' =>'roasted nuts','apiIngredientId'=>'12135'],
            ['name' =>'roasted peanuts','apiIngredientId'=>'16092'],
            ['name' =>'roasted red peppers','apiIngredientId'=>'11916'],
            ['name' =>'roma tomatoes','apiIngredientId'=>'10211529'],
            ['name' =>'romaine lettuce','apiIngredientId'=>'10111251'],
            ['name' =>'root vegetables','apiIngredientId'=>'10011298'],
            ['name' =>'rosemary','apiIngredientId'=>'2036'],
            ['name' =>'rotini pasta','apiIngredientId'=>'11320420'],
            ['name' =>'rotisserie chicken','apiIngredientId'=>'5348'],
            ['name' =>'round steak','apiIngredientId'=>'23617'],
            ['name' =>'rub','apiIngredientId'=>'1012034'],
            ['name' =>'rum extract','apiIngredientId'=>'12211111'],
            ['name' =>'runny honey','apiIngredientId'=>'19296'],
            ['name' =>'russet potatoes','apiIngredientId'=>'11353'],
            ['name' =>'rutabaga','apiIngredientId'=>'11435'],
            ['name' =>'rye bread','apiIngredientId'=>'18060'],
            ['name' =>'rye meal','apiIngredientId'=>'98905'],
            ['name' =>'saffron threads','apiIngredientId'=>'2037'],
            ['name' =>'sage','apiIngredientId'=>'2038'],
            ['name' =>'sage leaves','apiIngredientId'=>'99226'],
            ['name' =>'salad dressing','apiIngredientId'=>'4114'],
            ['name' =>'salami','apiIngredientId'=>'7071'],
            ['name' =>'salmon fillet','apiIngredientId'=>'15076'],
            ['name' =>'salsa','apiIngredientId'=>'6164'],
            ['name' =>'salsa verde','apiIngredientId'=>'27028'],
            ['name' =>'salt','apiIngredientId'=>'2047'],
            ['name' =>'salt and pepper','apiIngredientId'=>'1102047'],
            ['name' =>'salted butter','apiIngredientId'=>'1001001'],
            ['name' =>'saltine crackers','apiIngredientId'=>'18228'],
            ['name' =>'sandwich bun','apiIngredientId'=>'18353'],
            ['name' =>'sauerkraut','apiIngredientId'=>'11439'],
            ['name' =>'sausage','apiIngredientId'=>'1017063'],
            ['name' =>'sausage links','apiIngredientId'=>'1037063'],
            ['name' =>'scotch bonnet chili','apiIngredientId'=>'10011819'],
            ['name' =>'sea salt','apiIngredientId'=>'1012047'],
            ['name' =>'sea scallops','apiIngredientId'=>'10015172'],
            ['name' =>'seasoned bread crumbs','apiIngredientId'=>'18376'],
            ['name' =>'seasoned rice vinegar','apiIngredientId'=>'1032053'],
            ['name' =>'seasoned salt','apiIngredientId'=>'1042047'],
            ['name' =>'seasoning','apiIngredientId'=>'1042027'],
            ['name' =>'seasoning blend','apiIngredientId'=>'1032027'],
            ['name' =>'seeds','apiIngredientId'=>'93818'],
            ['name' =>'self-rising flour','apiIngredientId'=>'20129'],
            ['name' =>'semi sweet chocolate chips','apiIngredientId'=>'10019903'],
            ['name' =>'serrano chile','apiIngredientId'=>'11977'],
            ['name' =>'sesame oil','apiIngredientId'=>'4058'],
            ['name' =>'sesame seed hamburger buns','apiIngredientId'=>'10018350'],
            ['name' =>'sesame seeds','apiIngredientId'=>'12023'],
            ['name' =>'shallot','apiIngredientId'=>'11677'],
            ['name' =>'sharp cheddar cheese','apiIngredientId'=>'1031009'],
            ['name' =>'sheeps milk cheese','apiIngredientId'=>'1011019'],
            ['name' =>'shells','apiIngredientId'=>'11020420'],
            ['name' =>'sherry','apiIngredientId'=>'10114106'],
            ['name' =>'sherry','apiIngredientId'=>'10214106'],
            ['name' =>'sherry vinegar','apiIngredientId'=>'1012068'],
            ['name' =>'shiitake mushroom caps','apiIngredientId'=>'11238'],
            ['name' =>'short grain rice','apiIngredientId'=>'10120052'],
            ['name' =>'short pasta','apiIngredientId'=>'20499'],
            ['name' =>'short ribs','apiIngredientId'=>'10013149'],
            ['name' =>'shortbread cookies','apiIngredientId'=>'18192'],
            ['name' =>'shortcrust pastry','apiIngredientId'=>'10018338'],
            ['name' =>'shortening','apiIngredientId'=>'4615'],
            ['name' =>'shredded cheddar cheese','apiIngredientId'=>'1001009'],
            ['name' =>'shredded cheese','apiIngredientId'=>'1011026'],
            ['name' =>'shredded chicken','apiIngredientId'=>'1005114'],
            ['name' =>'shredded coconut','apiIngredientId'=>'12108'],
            ['name' =>'shredded mexican cheese blend','apiIngredientId'=>'1001251'],
            ['name' =>'shredded mexican cheese blend','apiIngredientId'=>'1251'],
            ['name' =>'shredded mozzarella','apiIngredientId'=>'1001026'],
            ['name' =>'silken tofu','apiIngredientId'=>'16161'],
            ['name' =>'sirloin steak','apiIngredientId'=>'23625'],
            ['name' =>'skim milk ricotta','apiIngredientId'=>'93630'],
            ['name' =>'skim vanilla greek yogurt','apiIngredientId'=>'99033'],
            ['name' =>'skin-on bone-in chicken leg quarters','apiIngredientId'=>'1005091'],
            ['name' =>'skinless boneless chicken breast halves','apiIngredientId'=>'1045062'],
            ['name' =>'skinless boneless chicken thighs','apiIngredientId'=>'5096'],
            ['name' =>'skinned black gram','apiIngredientId'=>'93718'],
            ['name' =>'slaw dressing','apiIngredientId'=>'43016'],
            ['name' =>'slaw mix','apiIngredientId'=>'10011109'],
            ['name' =>'slivered almonds','apiIngredientId'=>'10012061'],
            ['name' =>'smoked paprika','apiIngredientId'=>'1012028'],
            ['name' =>'smoked salmon','apiIngredientId'=>'15077'],
            ['name' =>'smoked sausage','apiIngredientId'=>'7916'],
            ['name' =>'smooth peanut butter','apiIngredientId'=>'16150'],
            ['name' =>'snapper fillets','apiIngredientId'=>'15101'],
            ['name' =>'snow peas','apiIngredientId'=>'11300'],
            ['name' =>'soda water','apiIngredientId'=>'14121'],
            ['name' =>'sour cream','apiIngredientId'=>'1056'],
            ['name' =>'sourdough bowl','apiIngredientId'=>'99169'],
            ['name' =>'sourdough bread','apiIngredientId'=>'10118029'],
            ['name' =>'soy milk','apiIngredientId'=>'16223'],
            ['name' =>'soy protein powder','apiIngredientId'=>'16122'],
            ['name' =>'soy sauce','apiIngredientId'=>'16124'],
            ['name' =>'spaghetti','apiIngredientId'=>'11420420'],
            ['name' =>'spaghetti squash','apiIngredientId'=>'11492'],
            ['name' =>'sparkling wine','apiIngredientId'=>'43155'],
            ['name' =>'spelt flour','apiIngredientId'=>'93823'],
            ['name' =>'spicy brown mustard','apiIngredientId'=>'1022046'],
            ['name' =>'spinach','apiIngredientId'=>'10011457'],
            ['name' =>'sprite','apiIngredientId'=>'14144'],
            ['name' =>'sprouts','apiIngredientId'=>'11001'],
            ['name' =>'squash','apiIngredientId'=>'10011485'],
            ['name' =>'sriracha sauce','apiIngredientId'=>'1016168'],
            ['name' =>'steaks','apiIngredientId'=>'23232'],
            ['name' =>'steel cut oats','apiIngredientId'=>'93695'],
            ['name' =>'stevia','apiIngredientId'=>'93628'],
            ['name' =>'stew meat','apiIngredientId'=>'10023618'],
            ['name' =>'stew vegetables','apiIngredientId'=>'11583'],
            ['name' =>'stock','apiIngredientId'=>'1006615'],
            ['name' =>'store-bought phyllo','apiIngredientId'=>'18338'],
            ['name' =>'stout','apiIngredientId'=>'93619'],
            ['name' =>'strawberries','apiIngredientId'=>'9316'],
            ['name' =>'strawberry jam','apiIngredientId'=>'10819297'],
            ['name' =>'strawberry jello','apiIngredientId'=>'10219172'],
            ['name' =>'stuffing','apiIngredientId'=>'18082'],
            ['name' =>'stuffing mix','apiIngredientId'=>'18081'],
            ['name' =>'sub rolls','apiIngredientId'=>'98940'],
            ['name' =>'sugar','apiIngredientId'=>'19335'],
            ['name' =>'sugar snap peas','apiIngredientId'=>'10011300'],
            ['name' =>'sugar syrup','apiIngredientId'=>'90480'],
            ['name' =>'sukrin sweetener','apiIngredientId'=>'99190'],
            ['name' =>'summer savory','apiIngredientId'=>'98961'],
            ['name' =>'summer squash','apiIngredientId'=>'11641'],
            ['name' =>'sunflower oil','apiIngredientId'=>'4584'],
            ['name' =>'sunflower seeds','apiIngredientId'=>'12036'],
            ['name' =>'sweet chilli sauce','apiIngredientId'=>'98962'],
            ['name' =>'sweet onion','apiIngredientId'=>'11294'],
            ['name' =>'sweet paprika','apiIngredientId'=>'1002028'],
            ['name' =>'sweet pickle juice','apiIngredientId'=>'93640'],
            ['name' =>'sweet pickle relish','apiIngredientId'=>'11945'],
            ['name' =>'sweet potato','apiIngredientId'=>'11507'],
            ['name' =>'sweet tea','apiIngredientId'=>'14355'],
            ['name' =>'sweetened coconut','apiIngredientId'=>'12109'],
            ['name' =>'sweetened condensed milk','apiIngredientId'=>'1095'],
            ['name' =>'sweetened shredded coconut','apiIngredientId'=>'12179'],
            ['name' =>'swiss chard','apiIngredientId'=>'11147'],
            ['name' =>'swiss cheese','apiIngredientId'=>'1040'],
            ['name' =>'taco seasoning mix','apiIngredientId'=>'2073'],
            ['name' =>'taco shells','apiIngredientId'=>'18360'],
            ['name' =>'tahini','apiIngredientId'=>'12698'],
            ['name' =>'tamari','apiIngredientId'=>'10116124'],
            ['name' =>'tapioca flour','apiIngredientId'=>'93696'],
            ['name' =>'tarragon','apiIngredientId'=>'2041'],
            ['name' =>'tart apple','apiIngredientId'=>'1029003'],
            ['name' =>'tea bags','apiIngredientId'=>'10111111'],
            ['name' =>'tequila','apiIngredientId'=>'10814037'],
            ['name' =>'teriyaki sauce','apiIngredientId'=>'6112'],
            ['name' =>'thai basil','apiIngredientId'=>'1012044'],
            ['name' =>'thai chiles','apiIngredientId'=>'11670'],
            ['name' =>'thai red curry paste','apiIngredientId'=>'93605'],
            ['name' =>'thick-cut bacon','apiIngredientId'=>'10310123'],
            ['name' =>'tilapia fillets','apiIngredientId'=>'15261'],
            ['name' =>'toast','apiIngredientId'=>'18070'],
            ['name' =>'toffee bits','apiIngredientId'=>'19383'],
            ['name' =>'tofu','apiIngredientId'=>'16213'],
            ['name' =>'tomatillos','apiIngredientId'=>'11954'],
            ['name' =>'tomato juice','apiIngredientId'=>'11886'],
            ['name' =>'tomato paste','apiIngredientId'=>'11887'],
            ['name' =>'tomato puree','apiIngredientId'=>'11547'],
            ['name' =>'tomato sauce','apiIngredientId'=>'11549'],
            ['name' =>'tomato soup','apiIngredientId'=>'6159'],
            ['name' =>'tomatoes','apiIngredientId'=>'11529'],
            ['name' =>'top blade steak','apiIngredientId'=>'13523'],
            ['name' =>'top round steak','apiIngredientId'=>'23636'],
            ['name' =>'Top Sirloin','apiIngredientId'=>'23584'],
            ['name' =>'tortilla','apiIngredientId'=>'18364'],
            ['name' =>'tortilla chips','apiIngredientId'=>'19056'],
            ['name' =>'triple sec','apiIngredientId'=>'14534'],
            ['name' =>'truffle oil','apiIngredientId'=>'1024053'],
            ['name' =>'tuna','apiIngredientId'=>'10015121'],
            ['name' =>'turbinado sugar','apiIngredientId'=>'19908'],
            ['name' =>'turkey','apiIngredientId'=>'5165'],
            ['name' =>'turkey breast','apiIngredientId'=>'5696'],
            ['name' =>'turkey kielbasa','apiIngredientId'=>'7955'],
            ['name' =>'turmeric','apiIngredientId'=>'2043'],
            ['name' =>'turnips','apiIngredientId'=>'11564'],
            ['name' =>'unbleached flour','apiIngredientId'=>'10020081'],
            ['name' =>'unsalted butter','apiIngredientId'=>'1145'],
            ['name' =>'unsmoked back bacon','apiIngredientId'=>'10130'],
            ['name' =>'unsweetened applesauce','apiIngredientId'=>'9019'],
            ['name' =>'unsweetened coconut milk','apiIngredientId'=>'12117'],
            ['name' =>'unsweetened shredded coconut','apiIngredientId'=>'10012108'],
            ['name' =>'vanilla bean','apiIngredientId'=>'93622'],
            ['name' =>'vanilla bean paste','apiIngredientId'=>'93813'],
            ['name' =>'vanilla essence','apiIngredientId'=>'1012050'],
            ['name' =>'vanilla extract','apiIngredientId'=>'2050'],
            ['name' =>'vanilla frosting','apiIngredientId'=>'10019230'],
            ['name' =>'vanilla instant pudding mix','apiIngredientId'=>'19206'],
            ['name' =>'vanilla protein powder','apiIngredientId'=>'99076'],
            ['name' =>'vanilla wafers','apiIngredientId'=>'18609'],
            ['name' =>'vanilla yogurt','apiIngredientId'=>'1119'],
            ['name' =>'vegan cheese','apiIngredientId'=>'93701'],
            ['name' =>'vegan chocolate chips','apiIngredientId'=>'98848'],
            ['name' =>'vegan margarine','apiIngredientId'=>'4673'],
            ['name' =>'vegetable broth','apiIngredientId'=>'6615'],
            ['name' =>'vegetable oil','apiIngredientId'=>'4513'],
            ['name' =>'vegetarian bacon','apiIngredientId'=>'16542'],
            ['name' =>'vermouth','apiIngredientId'=>'14132'],
            ['name' =>'vinaigrette','apiIngredientId'=>'4135'],
            ['name' =>'vinegar','apiIngredientId'=>'2053'],
            ['name' =>'vodka','apiIngredientId'=>'14051'],
            ['name' =>'walnuts','apiIngredientId'=>'12155'],
            ['name' =>'water','apiIngredientId'=>'14412'],
            ['name' =>'water chestnuts','apiIngredientId'=>'11590'],
            ['name' =>'water-packed tuna','apiIngredientId'=>'15121'],
            ['name' =>'watercress','apiIngredientId'=>'11591'],
            ['name' =>'watermelon chunks','apiIngredientId'=>'9326'],
            ['name' =>'wheat bran','apiIngredientId'=>'20077'],
            ['name' =>'wheat germ','apiIngredientId'=>'20078'],
            ['name' =>'whipped cream','apiIngredientId'=>'1054'],
            ['name' =>'whipped topping','apiIngredientId'=>'42135'],
            ['name' =>'whipping cream','apiIngredientId'=>'1001053'],
            ['name' =>'whiskey','apiIngredientId'=>'14052'],
            ['name' =>'white balsamic vinegar','apiIngredientId'=>'1012069'],
            ['name' =>'white bread','apiIngredientId'=>'18069'],
            ['name' =>'white cake mix','apiIngredientId'=>'18137'],
            ['name' =>'white cheddar','apiIngredientId'=>'1011009'],
            ['name' =>'white chocolate','apiIngredientId'=>'19087'],
            ['name' =>'white chocolate chips','apiIngredientId'=>'10019087'],
            ['name' =>'white onion','apiIngredientId'=>'10611282'],
            ['name' =>'white pepper','apiIngredientId'=>'2032'],
            ['name' =>'white whole wheat flour','apiIngredientId'=>'93824'],
            ['name' =>'white wine','apiIngredientId'=>'14106'],
            ['name' =>'white wine vinegar','apiIngredientId'=>'1002068'],
            ['name' =>'whole allspice berries','apiIngredientId'=>'1002001'],
            ['name' =>'whole chicken','apiIngredientId'=>'5006'],
            ['name' =>'whole coriander seeds','apiIngredientId'=>'2013'],
            ['name' =>'whole cranberry sauce','apiIngredientId'=>'9081'],
            ['name' =>'whole kernel corn','apiIngredientId'=>'11177'],
            ['name' =>'whole star anise','apiIngredientId'=>'1012002'],
            ['name' =>'whole wheat bread','apiIngredientId'=>'18075'],
            ['name' =>'whole wheat flour','apiIngredientId'=>'20080'],
            ['name' =>'whole wheat tortillas','apiIngredientId'=>'93675'],
            ['name' =>'whole-grain mustard','apiIngredientId'=>'1012046'],
            ['name' =>'wine','apiIngredientId'=>'14084'],
            ['name' =>'wine vinegar','apiIngredientId'=>'2068'],
            ['name' =>'winter squash','apiIngredientId'=>'10111485'],
            ['name' =>'won ton wraps','apiIngredientId'=>'10018368'],
            ['name' =>'worcestershire sauce','apiIngredientId'=>'6971'],
            ['name' =>'wraps','apiIngredientId'=>'10018364'],
            ['name' =>'xanthan gum','apiIngredientId'=>'93626'],
            ['name' =>'yeast','apiIngredientId'=>'18375'],
            ['name' =>'yellow bell pepper','apiIngredientId'=>'11951'],
            ['name' =>'yellow cake mix','apiIngredientId'=>'18144'],
            ['name' =>'yellow onion','apiIngredientId'=>'10511282'],
            ['name' =>'yogurt','apiIngredientId'=>'1116'],
            ['name' =>'yukon gold potato','apiIngredientId'=>'10211362'],
        ];
        Ingredient::insert($ingredients);

    }
}
